<div class="container">
    <div class="row">
        <h2 class="h2"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">TJG Micro Framework</h1>
            <p>
                Este é um micro framework MVC em PHP, construído como execício do conteúdo didático do curso "Micro Framework do Zero" disponibilizado no canal TJG Web no Youtube.
            </p>
            <p>
                O intúito do curso é exclarecer os conceitos e o funcionamento dos grandes frameworks de renome já consagrados hoje no mercado. Depois esse curso o aluno entenderá melhor os cursos oferecidos na internet de frameworks como Laravel, Zend, CakePHP, etc.
            </p>
        </div>
    </div>
</div>