<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">TJG Micro Framework</h1>
            <p>
                Este é um micro framework MVC em PHP, construído como execício do conteúdo didático do curso "Micro Framework do Zero" disponibilizado através do Youtube no canal TJG Web.
            </p>
            <p>
                O intúito do curso é dar uma base mais sólida e exclarecer os conceitos e o funcionamento do ciclo de vida de uma aplicação web seguindo padrões MVC. Depois deste curso, o aluno entenderá melhor o conteúdo de outros cursos oferecidos na internet de frameworks como Laravel, Zend, CakePHP, etc.
            </p>
        </div>
    </div>
</div>