<div class="container">
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->getPageTitle() ?></h3>
                </div>
                <div class="panel-body">

                    <?php $this->renderView('alerts/_errors'); ?>

                    <form action="/login/auth" method="post" accept-charset="utf-8">

                        <div class="form-group">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="text" name="email" class="form-control"
                                   value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>">
                        </div>

                        <div class="form-group">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" name="password" class="form-control">
                        </div>

                        <button type="submit" class="btn btn-primary">
                            <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i> Login
                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>