<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/post/store" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo ($this->errors['title']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Title</label>
                    <input type="text" name="title" class="form-control"
                           value="<?php echo (isset($this->inputs['title'])) ? $this->inputs['title'] : '' ?>">
                    <?php if ($this->errors['title']): ?>
                        <span class="help-block"><?php echo $this->errors['title'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['content']) ? 'has-error' : '' ?>">
                    <label for="content" class="control-label">Content</label>
                    <textarea name="content" class="form-control"
                              rows="10"><?php echo (isset($this->inputs['content'])) ? $this->inputs['content'] : '' ?></textarea>
                    <?php if ($this->errors['content']): ?>
                        <span class="help-block"><?php echo $this->errors['content'] ?></span>
                    <?php endif; ?>
                </div>
            </div>

            <div class="col-sm-2">
                <div class="form-group <?php echo ($this->errors['category_id']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Categories</label>
                    <?php foreach ($this->view->categories as $cat) : ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="category_id[]"
                                       value="<?php echo $cat->id ?>"> <?php echo $cat->name ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="col-xs-12">
                <a href="/posts" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>