<div class="container">

    <h1 class="h1"><?php echo $this->getPageTitle() ?></h1>

    <form action="/post/<?php echo $this->view->post->id ?>/update" method="post" accept-charset="utf-8">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control" value="<?php echo $this->view->post->title ?>">
        </div>
        <div class="form-group">
            <label for="title">Content</label>
            <textarea name="content" class="form-control" rows="10"><?php echo $this->view->post->content ?></textarea>
        </div>
        <a href="/posts" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

</div>