<div class="container">
    <h1 class="h1">
        <?php $this->getPageTitle(); ?>
        <a href="/post/create" class="btn btn-primary pull-right">
            <i class="glyphicon glyphicon-plus-sign"></i> New post
        </a>
    </h1>

    <?php foreach ($this->view->posts as $post): ?>
        <h3 class="h3">
            <a href="/post/<?php echo $post->id; ?>/show"><?php echo $post->title; ?></a>
        </h3>
        <p class="text-justify"><?php echo $post->content; ?></p>
        <p class="text-right">
            <a href="/post/<?php echo $post->id ?>/edit" class="btn btn-warning btn-xs">
                <i class="glyphicon glyphicon-pencil"></i>
            </a>
            <a href="/post/<?php echo $post->id ?>/delete" class="btn btn-danger btn-xs" onclick="return confirm('Deletar este post?')">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </p>
        <hr/>
    <?php endforeach; ?>
</div>