<div class="container">
    <h1 class="h1">
        <?php $this->getPageTitle(); ?>
        <a href="/post/create" class="btn btn-primary pull-right">
            <i class="glyphicon glyphicon-plus-sign"></i> New post
        </a>
    </h1>

    <?php foreach ($this->view->posts as $post): ?>
        <h3 class="h3">
            <a href="/post/<?php echo $post->id; ?>/show"><?php echo $post->title; ?></a>
        </h3>
        <p class="text-justify"><?php echo $post->content; ?></p>
        <hr/>
    <?php endforeach; ?>
</div>