<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->getPageTitle('|') ?>TJG Micro Framework</title>

    <link href="/assets/css/style.css" rel="stylesheet">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<?php require_once __DIR__ . "/menu.phtml" ?>

<?php $this->content() ?>

<!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
<script src="/assets/js/jquery.min.js"></script>
<!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>