<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="/favicon.ico" class="pull-left" />&nbsp;&nbsp;Micro Framework
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/posts">Blog</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if($this->auth->check()) : ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                           <i class="glyphicon glyphicon-user"></i> <?php echo $this->auth->name() ?> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
                        </ul>
                    </li>
                <?php else : ?>
                    <li><a href="/login"><i class="glyphicon glyphicon-log-in"></i> Login</a></li>
                    <li><a href="/user/create"><i class="glyphicon glyphicon-pencil"></i> Register</a></li>
                <?php endif; ?>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>